"""drop plugin_repo table

Revision ID: 0012
Revises: 0011
Create Date: 2026-05-06

接在 0011_command_aliases 之后；初版误写为 down_revision="0010"
导致与 0011 构成分叉，汇总验收时修正为 0011。
"""

from __future__ import annotations

from alembic import op

revision = "0012"
down_revision = "0011"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("DROP TABLE IF EXISTS plugin_repo CASCADE;")


def downgrade() -> None:
    op.execute(
        """
        CREATE TABLE plugin_repo (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            url TEXT NOT NULL,
            enabled BOOLEAN NOT NULL DEFAULT true,
            last_synced_at TIMESTAMPTZ
        );
        """
    )
